version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Mapear a porta do MongoDB para o host
    volumes:
      - mongo_data:/data/db  # Persistir dados do MongoDB em um volume

  flask-api:
    build: .
    container_name: flask-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:  # Volume para armazenar os dados
