services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_api_estrela:/var/lib/mysql
    networks:
      - api-estrela

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - api-estrela

  populador:
    container_name: populador
    restart: always
    build: 
      context: .
      dockerfile: ./populador/Dockerfile
    depends_on:
      - mysql
    networks:
      - api-estrela

  api-estrela:
    container_name: api-estrela
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - mysql
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    networks:
      - api-estrela

volumes:
  mysql_data_api_estrela:

networks:
  api-estrela:
    driver: bridge